name: client
description: Dart package to manage {Feature} data and domain layers.
version: 0.0.1+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  # Scope packages
  errors:
    git:
      url: git://github.com/NoScopeDevs/errors
  network_manager:
    git:
      url: git://github.com/NoScopeDevs/network_manager

  # Feature packages
  avatar:
    path: ../avatar
  cypher:
    path: ../cypher

  dartz: ^0.9.2
  equatable: ^1.2.6
  freezed_annotation:
  json_annotation: ^3.1.1
  meta:
  path:

dev_dependencies:
  # code generators
  build_runner:
  freezed:
  json_serializable: ^3.5.1

  # testing
  mockito:
  test:

  # static analysis
  very_good_analysis:
