name: listen2help
description: A Flutter application to help therapists connect with their patients.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code generator for assets, fonts, colors, etc
  flutter_gen: ^1.3.1
  # app icons
  flutter_launcher_icons: ^0.8.1
  # abstract classes mock for testing
  mockito: ^4.1.3
  # linter
  very_good_analysis: ^1.0.4

flutter:
  uses-material-design: true
