name: listen2help
description: A Flutter application to help therapists connect with their patients.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Feature packages
  authentication:
    path: packages/authentication

  cupertino_icons: ^1.0.0
  flutter_riverpod: ^0.12.1
  flutter_svg: ^0.19.0
  freezed_annotation: any
  i18n_extension: ^1.4.5
  meta: ^1.2.4
  package_info: ^0.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # utility to run code generators
  build_runner: any
  # code generator for assets, fonts, colors, etc
  flutter_gen: ^1.3.1
  # app icons
  flutter_launcher_icons: ^0.8.1
  # abstract classes mock for testing
  mockito: ^4.1.3
  # data & union classes and equality
  freezed: any
  # classes & method that support json code generation
  json_serializable: any
  # linter
  very_good_analysis: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    # - assets/json/
    # - assets/img/
    # - assets/svg/

  # fonts:
  #   - family: Graphik
  #     fonts:
  #       - asset: assets/fonts/Graphik-Regular.ttf
  #   - family: GraphikBold
  #     fonts:
  #       - asset: assets/fonts/Graphik-Semibold.ttf
  #         weight: 700

flutter_gen:
  output: lib/src/gen/

  integrations:
    flutter_svg: true
#
# flutter_icons:
#   image_path_android: "assets/img/logo.png"
#   image_path_ios: "assets/img/logo.png"
#   android: true
#   ios: true
