name: authentication
description: Dart package which handles authentication domain and data layers.
version: 1.0.0

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  # GitHub packages
  errors:
    git:
      url: git://github.com/NoScopeDevs/errors
  network_manager:
    git:
      url: git://github.com/NoScopeDevs/network_manager

  # 3rd-party packages
  dartz: ^0.9.2
  dio: ^3.0.10
  freezed_annotation: any
  hive: ^1.4.4+1
  meta: ^1.2.4

dev_dependencies:
  build_runner: any
  freezed: any
  json_serializable: any
  test: ^1.14.4
  very_good_analysis: ^1.0.4
